// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/archive/{id}": {
            "get": {
                "description": "Retrieve a specific archive",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Archives"
                ],
                "summary": "Retrieve a specific archive",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Identifier for the archive",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved archive",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Archive not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/archives": {
            "get": {
                "description": "Retrieve a list of all archives",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Archives"
                ],
                "summary": "Retrieve a list of all archives",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved list of archives",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Archives not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deleteArchive/{id}": {
            "delete": {
                "description": "Delete a specific archive",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Archives"
                ],
                "summary": "Delete a specific archive",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Identifier for the archive to be deleted",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully deleted archive",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Archive not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
